# Generated by Django 4.1.4 on 2023-01-02 14:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('equipment_needed', models.ManyToManyField(to='WorkoutTracker.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Muscle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load', models.IntegerField(null=True)),
                ('repetitions', models.IntegerField()),
                ('is_loaded', models.BooleanField(default=True)),
                ('duration', models.IntegerField(null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkoutTracker.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_of_workout', models.TimeField(auto_created=True, default=datetime.datetime(2023, 1, 2, 14, 57, 7, 618745))),
                ('date', models.DateField(auto_now=True)),
                ('end_of_workout', models.TimeField()),
                ('comments', models.TextField()),
                ('is_template', models.BooleanField(default=False)),
                ('sets', models.ManyToManyField(to='WorkoutTracker.set')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('workout', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='WorkoutTracker.workout')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('workout_templates', models.ManyToManyField(to='WorkoutTracker.workouttemplate')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='main_muscle_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkoutTracker.muscle'),
        ),
    ]
