# Generated by Django 4.1.4 on 2023-01-09 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('equipment_needed', models.ManyToManyField(to='WorkoutTracker.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Muscle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('start_of_workout', models.TimeField(auto_now_add=True)),
                ('end_of_workout', models.TimeField(null=True)),
                ('comments', models.TextField(null=True)),
                ('is_template', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Wset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load', models.IntegerField(null=True)),
                ('repetitions', models.IntegerField()),
                ('is_loaded', models.BooleanField(default=True)),
                ('duration', models.IntegerField(null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkoutTracker.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('workout', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='WorkoutTracker.workout')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('workout_templates', models.ManyToManyField(to='WorkoutTracker.workouttemplate')),
            ],
        ),
        migrations.AddField(
            model_name='workout',
            name='wsets',
            field=models.ManyToManyField(to='WorkoutTracker.wset'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='main_muscle_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkoutTracker.muscle'),
        ),
    ]
