# Generated by Django 4.1.4 on 2023-01-09 18:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutTracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wset',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
