# Generated by Django 4.1.4 on 2023-01-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutTracker', '0002_alter_workout_date_alter_workout_start_of_workout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='comments',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='end_of_workout',
            field=models.TimeField(null=True),
        ),
    ]
