# Generated by Django 4.1.4 on 2023-01-09 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutTracker', '0002_wset_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='is_template',
        ),
        migrations.RemoveField(
            model_name='workouttemplate',
            name='workout',
        ),
        migrations.AddField(
            model_name='workout',
            name='workout_template',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='WorkoutTracker.workouttemplate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workouttemplate',
            name='wsets',
            field=models.ManyToManyField(to='WorkoutTracker.wset'),
        ),
    ]
