# Generated by Django 4.1.4 on 2023-02-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutTracker', '0003_set_created_set_updated_workoutplan_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='set',
            name='is_loaded',
        ),
        migrations.AddField(
            model_name='workouttemplate',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
