# Generated by Django 4.1.4 on 2023-01-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutTracker', '0003_remove_workout_is_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wset',
            name='in_exercise_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wset',
            name='in_workout_order',
            field=models.IntegerField(default=0),
        ),
    ]
