# Generated by Django 4.1.4 on 2023-01-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutTracker', '0004_wset_in_exercise_order_wset_in_workout_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
