# Generated by Django 4.1.4 on 2023-02-18 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WorkoutTracker', '0005_set_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutplantemplates',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='workoutplantemplates',
            name='template',
        ),
        migrations.AddField(
            model_name='exercise',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='set',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workout',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workouttemplate',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workouttemplate',
            name='sample',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='WorkoutPlan',
        ),
        migrations.DeleteModel(
            name='WorkoutPlanTemplates',
        ),
    ]
