# Generated by Django 4.1.4 on 2023-02-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutTracker', '0008_workouttemplate_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouttemplate',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
