# Generated by Django 4.1.4 on 2023-02-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutTracker', '0009_alter_workouttemplate_finished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workouttemplate',
            name='finished',
        ),
        migrations.AddField(
            model_name='workout',
            name='finished',
            field=models.BooleanField(default=True),
        ),
    ]
