# Generated by Django 4.1.4 on 2023-02-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutTracker', '0010_remove_workouttemplate_finished_workout_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
