# Generated by Django 4.1.4 on 2023-02-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutTracker', '0012_alter_exercise_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='load',
            field=models.FloatField(null=True),
        ),
    ]
