# Generated by Django 4.1.4 on 2023-02-24 22:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WorkoutTracker', '0013_alter_set_load'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='sample',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='workouttemplate',
            unique_together={('owner', 'name')},
        ),
    ]
