# Generated by Django 4.1.4 on 2023-02-24 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutTracker', '0014_alter_exercise_sample_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouttemplate',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
