# Generated by Django 4.1.4 on 2023-02-24 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutTracker', '0016_alter_equipment_name_alter_muscle_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='equipment_needed',
            field=models.ManyToManyField(blank=True, to='WorkoutTracker.equipment'),
        ),
    ]
