# Generated by Django 4.1.4 on 2023-02-24 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutTracker', '0017_alter_exercise_equipment_needed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='equipment_needed',
            field=models.ManyToManyField(blank=True, null=True, to='WorkoutTracker.equipment'),
        ),
    ]
