# Generated by Django 4.1.4 on 2023-03-03 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutTracker', '0017_alter_exercise_equipment_needed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='owner',
        ),
    ]
